### ISSUE TITLE
Skyhook incompatible with latest version of skylark

### ISSUE THREAD

**Issue by garethr** [hippogryph/skyhook#4]
I updated to master just now and hit an issue on compile, specifically:

```
vendor\github.com\hippogryph\skyhook\convert\conv.go:16:2: undefined: resolve.AllowFreeze
```

It looks like freeze was just removed:

https://github.com/google/skylark/commit/ffb61b871f41afe93fdd2ab826a4f352cb770a83

**Comment by natefinch** [comment]
this is fixed
